define(['require'],
    function(require) {
        /**
         * Controller for index generated by Appery.io
         * @module index
         */
        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.activeScreen = Apperyio.EntityAPI('ActiveScreen');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                $scope.visionStatus = {};
            };
        }
        return ['$scope', 'Apperyio', controller];
    });